document.querySelector('.wnd-fe') &&
  [...document.querySelectorAll('.c')].forEach((e) => {
    const t = e.querySelector('.b-text:only-child');
    t &&
      '' === t.querySelector('.b-text-c').innerText &&
      e.classList.add('column-empty');
  });

var wnd = wnd || {};
wnd.$data = {
  image_content_items: {
    wnd_ThumbnailBlock_1: {
      id: 'wnd_ThumbnailBlock_1',
      type: 'wnd.pc.ThumbnailBlock',
    },
    wnd_HeaderSection_header_main_955021093: {
      id: 'wnd_HeaderSection_header_main_955021093',
      type: 'wnd.pc.HeaderSection',
    },
    wnd_ImageBlock_854474252: {
      id: 'wnd_ImageBlock_854474252',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_Section_text_image_224943160: {
      id: 'wnd_Section_text_image_224943160',
      type: 'wnd.pc.Section',
    },
    wnd_Section_text_image_934651578: {
      id: 'wnd_Section_text_image_934651578',
      type: 'wnd.pc.Section',
    },
    wnd_ImageBlock_676390311: {
      id: 'wnd_ImageBlock_676390311',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_Section_two_cols_959848513: {
      id: 'wnd_Section_two_cols_959848513',
      type: 'wnd.pc.Section',
    },
    wnd_ImageBlock_36806: {
      id: 'wnd_ImageBlock_36806',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_59679: {
      id: 'wnd_ImageBlock_59679',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_30638: {
      id: 'wnd_ImageBlock_30638',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_57672: {
      id: 'wnd_ImageBlock_57672',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_34345: {
      id: 'wnd_ImageBlock_34345',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_76822: {
      id: 'wnd_ImageBlock_76822',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_84840: {
      id: 'wnd_ImageBlock_84840',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_258468000: {
      id: 'wnd_ImageBlock_258468000',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_532724920: {
      id: 'wnd_ImageBlock_532724920',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_236627507: {
      id: 'wnd_ImageBlock_236627507',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_858621554: {
      id: 'wnd_ImageBlock_858621554',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_625389352: {
      id: 'wnd_ImageBlock_625389352',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_961692459: {
      id: 'wnd_ImageBlock_961692459',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_LogoBlock_579905451: {
      id: 'wnd_LogoBlock_579905451',
      type: 'wnd.pc.LogoBlock',
    },
    wnd_FooterSection_footer_927478088: {
      id: 'wnd_FooterSection_footer_927478088',
      type: 'wnd.pc.FooterSection',
    },
  },
  svg_content_items: {
    wnd_ImageBlock_854474252: {
      id: 'wnd_ImageBlock_854474252',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_676390311: {
      id: 'wnd_ImageBlock_676390311',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_36806: {
      id: 'wnd_ImageBlock_36806',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_59679: {
      id: 'wnd_ImageBlock_59679',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_30638: {
      id: 'wnd_ImageBlock_30638',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_57672: {
      id: 'wnd_ImageBlock_57672',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_34345: {
      id: 'wnd_ImageBlock_34345',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_76822: {
      id: 'wnd_ImageBlock_76822',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_84840: {
      id: 'wnd_ImageBlock_84840',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_258468000: {
      id: 'wnd_ImageBlock_258468000',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_532724920: {
      id: 'wnd_ImageBlock_532724920',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_236627507: {
      id: 'wnd_ImageBlock_236627507',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_858621554: {
      id: 'wnd_ImageBlock_858621554',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_625389352: {
      id: 'wnd_ImageBlock_625389352',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_ImageBlock_961692459: {
      id: 'wnd_ImageBlock_961692459',
      type: 'wnd.pc.ImageBlock',
    },
    wnd_LogoBlock_579905451: {
      id: 'wnd_LogoBlock_579905451',
      type: 'wnd.pc.LogoBlock',
    },
  },
  content_items: [],
  project_info: {
    isMultilanguage: false,
    isMulticurrency: false,
    eshop_tax_enabled: '1',
    country_code: '',
    contact_state: null,
    eshop_tax_type: 'VAT',
    eshop_discounts: true,
  },
  eshopSettings: {
    ESHOP_SETTINGS_DISPLAY_PRICE_WITHOUT_VAT: false,
    ESHOP_SETTINGS_DISPLAY_ADDITIONAL_VAT: false,
    ESHOP_SETTINGS_DISPLAY_SHIPPING_COST: false,
  },
};

wnd.$system = {
  fileSystemType: 'aws_s3',
  localFilesPath: 'https://www.hittakonkurser.se/_files/',
  awsS3FilesPath:
    'https://addd596a22.clvaw-cdnwnd.com/7aee85e1fc8747e649291e2a8e158614/',
  staticFiles: 'https://d1di2lzuh97fh2.cloudfront.net/files',
  isCms: false,
  staticCDNServers: ['https://d1di2lzuh97fh2.cloudfront.net/'],
  fileUploadAllowExtension: [
    'jpg',
    'jpeg',
    'jfif',
    'png',
    'gif',
    'bmp',
    'ico',
    'svg',
    'webp',
    'tiff',
    'pdf',
    'doc',
    'docx',
    'ppt',
    'pptx',
    'pps',
    'ppsx',
    'odt',
    'xls',
    'xlsx',
    'txt',
    'rtf',
    'mp3',
    'wma',
    'wav',
    'ogg',
    'amr',
    'flac',
    'm4a',
    '3gp',
    'avi',
    'wmv',
    'mov',
    'mpg',
    'mkv',
    'mp4',
    'mpeg',
    'm4v',
    'swf',
    'gpx',
    'stl',
    'csv',
    'xml',
    'txt',
    'dxf',
    'dwg',
    'iges',
    'igs',
    'step',
    'stp',
  ],
  maxUserFormFileLimit: 4194304,
  frontendLanguage: 'sv',
  backendLanguage: 'en-us',
  frontendLanguageId: '1',
  page: {
    id: 200003350,
    identifier: 'home',
    template: {
      id: 200000086,
      styles: {
        typography: 't-27_new',
        scheme: 'cs-deep',
        additiveColor: 'ac-wnd',
        acHeadings: false,
        acSubheadings: false,
        acIcons: false,
        acOthers: false,
        imageStyle: 'img-d-n',
        imageHover: 'img-h-n',
        imageTitle: 'img-t-o',
        buttonStyle: 'b-btn-r',
        buttonSize: 'b-btn-s-m',
        buttonDecoration: 'b-btn-dbb',
        buttonBorders: 'b-btn-bw-1',
        lineStyle: 'line-solid',
        eshopGridItemStyle: 'b-e-ds',
        formStyle: 'default',
        menuType: '',
        menuStyle: 'menu-default',
        lightboxStyle: 'lbox-d',
        columnSpaces: 'c-s-n',
        sectionWidth: 'wnd-w-narrow',
        sectionSpace: 'wnd-s-normal',
        layoutType: 'l-default',
        layoutDecoration: 'l-d-none',
        background: { default: null },
        backgroundSettings: { default: '' },
        acMenu: true,
        buttonWeight: 't-btn-fw-s',
        productWeight: 't-pd-fw-s',
        menuWeight: 't-nav-fw-l',
        headerBarStyle: '',
        headerType: 'default',
        typoTitleSizes: 't-t-fs-s',
        typoTitleWeights: 't-t-fw-s',
        typoTitleSpacings: 't-t-sp-n',
        typoTitleDecorations: 't-t-d-n',
        typoHeadingSizes: 't-h-fs-s',
        typoHeadingWeights: 't-h-fw-s',
        typoHeadingSpacings: 't-h-sp-n',
        typoSubtitleSizes: 't-s-fs-s',
        typoSubtitleWeights: 't-s-fw-m',
        typoSubtitleSpacings: 't-s-sp-n',
        typoSubtitleDecorations: 't-s-d-n',
        typoParagraphSizes: 't-p-fs-s',
        typoParagraphWeights: 't-p-fw-m',
        typoParagraphSpacings: 't-p-sp-n',
        typoBlockquoteSizes: 't-bq-fs-s',
        typoBlockquoteWeights: 't-bq-fw-m',
        typoBlockquoteSpacings: 't-bq-sp-n',
        typoBlockquoteDecorations: 't-bq-d-q',
        menuTextTransform: 't-nav-tt-u',
      },
    },
    layout: 'homepage',
    name: 'Hem',
    html_title:
      'Fynda konkursbon, varulager, bilar, hela konkursbolag, konkursauktioner...',
    language: 'sv',
    langId: 1,
    isHomepage: true,
    meta_description:
      'Sveriges alla konkursbon, till 30-70% av marknadspriset. Direktkontakt - inga mellanh\u00e4nder. L\u00e4gg bud bekv\u00e4mt hemifr\u00e5n. ',
    meta_keywords:
      'konkursbon, konkurser, hitta konkurser, varulager, restpartier, klipp, l\u00f6nsamma aff\u00e4rer ',
    header_code: '',
    footer_code: '',
    styles: {
      pageBased: {
        navline: {
          style: {
            sectionColor: 'sc-none',
            sectionWidth: 'wnd-w-wide',
            sectionHeight: 'wnd-nh-l',
          },
        },
      },
    },
    countFormsEntries: [],
  },
  listingsPrefix: '/l/',
  productPrefix: '/p/',
  cartPrefix: '/cart/',
  checkoutPrefix: '/checkout/',
  searchPrefix: '/search/',
  isCheckout: false,
  isEshop: false,
  hasBlog: true,
  isProductDetail: false,
  isListingDetail: false,
  listing_page: [],
  hasEshopAnalytics: false,
  gTagId: null,
  gAdsId: null,
  format: {
    be: {
      DATE_TIME: {
        mask: '%m/%d/%Y %H:%M',
        regexp:
          '^(((0?[1-9]|1[0-2])\\/(0?[1-9]|[1,2][0-9]|3[0,1])\\/[0-9]{1,4})(( [0-1][0-9]| 2[0-3]):[0-5][0-9])?|(([0-9]{4}(0[1-9]|1[0-2])(0[1-9]|[1,2][0-9]|3[0,1])(0[0-9]|1[0-9]|2[0-3])[0-5][0-9][0-5][0-9])))?$',
      },
      DATE: {
        mask: '%m/%d/%Y',
        regexp:
          '^((0?[1-9]|1[0-2])\\/(0?[1-9]|[1,2][0-9]|3[0,1])\\/[0-9]{1,4})$',
      },
      CURRENCY: {
        mask: {
          point: '.',
          thousands: ',',
          decimals: 2,
          mask: '%s',
          zerofill: true,
        },
      },
    },
    fe: {
      DATE_TIME: {
        mask: '%d.%m.%Y %H:%M',
        regexp:
          '^(((0?[1-9]|[1,2][0-9]|3[0,1])\\.(0?[1-9]|1[0-2])\\.[0-9]{1,4})(( [0-1][0-9]| 2[0-3]):[0-5][0-9])?|(([0-9]{4}(0[1-9]|1[0-2])(0[1-9]|[1,2][0-9]|3[0,1])(0[0-9]|1[0-9]|2[0-3])[0-5][0-9][0-5][0-9])))?$',
      },
      DATE: {
        mask: '%d.%m.%Y',
        regexp:
          '^((0?[1-9]|[1,2][0-9]|3[0,1])\\.(0?[1-9]|1[0-2])\\.[0-9]{1,4})$',
      },
      CURRENCY: {
        mask: {
          point: ',',
          thousands: ' ',
          decimals: 2,
          mask: '%s',
          zerofill: true,
          ignoredZerofill: true,
        },
      },
    },
  },
  e_product: null,
  listing_item: null,
  feReleasedFeatures: {
    eshopPriceDisplaySettings: true,
    dualCurrency: false,
    HeurekaSatisfactionSurvey: false,
    useOnlyDefaultFreeBar: true,
    productAvailability: false,
  },
  labels: {
    'dualCurrency.fixedRate': '',
    'invoicesGenerator.W2EshopInvoice.alreadyPayed':
      'Betala inte! - Redan betalat',
    'invoicesGenerator.W2EshopInvoice.amount': 'Kvantitet:',
    'invoicesGenerator.W2EshopInvoice.contactInfo': 'Kontaktinformation:',
    'invoicesGenerator.W2EshopInvoice.couponCode': 'Kupongskod:',
    'invoicesGenerator.W2EshopInvoice.customer': 'Kund:',
    'invoicesGenerator.W2EshopInvoice.dateOfIssue': 'Utf\u00e4rdat den:',
    'invoicesGenerator.W2EshopInvoice.dateOfTaxableSupply':
      'Datum f\u00f6r skattepliktig leverans:',
    'invoicesGenerator.W2EshopInvoice.dic': 'Momsnummer:',
    'invoicesGenerator.W2EshopInvoice.discount': 'Rabatt',
    'invoicesGenerator.W2EshopInvoice.dueDate': 'F\u00f6rfallodatum:',
    'invoicesGenerator.W2EshopInvoice.email': 'E-postadress:',
    'invoicesGenerator.W2EshopInvoice.filenamePrefix': 'Kvitto-',
    'invoicesGenerator.W2EshopInvoice.fiscalCode': 'Identifikationsnummer:',
    'invoicesGenerator.W2EshopInvoice.freeShipping': 'Gratis frakt',
    'invoicesGenerator.W2EshopInvoice.ic': 'Organisationsnummer:',
    'invoicesGenerator.W2EshopInvoice.invoiceNo': 'Kvittonummer:',
    'invoicesGenerator.W2EshopInvoice.invoiceNoTaxed':
      'Kvitto - Skattefakturanummer',
    'invoicesGenerator.W2EshopInvoice.notVatPayers': 'Ej momsregistrerad',
    'invoicesGenerator.W2EshopInvoice.orderNo': 'Ordernummer:',
    'invoicesGenerator.W2EshopInvoice.paymentPrice': 'Pris betalningsmetod:',
    'invoicesGenerator.W2EshopInvoice.pec': 'PEC:',
    'invoicesGenerator.W2EshopInvoice.phone': 'Telefon:',
    'invoicesGenerator.W2EshopInvoice.priceExTax': 'Pris exkl. moms:',
    'invoicesGenerator.W2EshopInvoice.priceIncludingTax': 'Pris inkl. moms:',
    'invoicesGenerator.W2EshopInvoice.product': 'Produkt:',
    'invoicesGenerator.W2EshopInvoice.productNr': 'Produktnummer:',
    'invoicesGenerator.W2EshopInvoice.recipientCode': 'Mottagarkod:',
    'invoicesGenerator.W2EshopInvoice.shippingAddress': 'Leveransadress:',
    'invoicesGenerator.W2EshopInvoice.shippingPrice': 'Leveranspris:',
    'invoicesGenerator.W2EshopInvoice.subtotal': 'Delsumma:',
    'invoicesGenerator.W2EshopInvoice.sum': 'Totalt:',
    'invoicesGenerator.W2EshopInvoice.supplier': 'Leverant\u00f6r:',
    'invoicesGenerator.W2EshopInvoice.tax': 'Moms:',
    'invoicesGenerator.W2EshopInvoice.total': 'Totalt:',
    'invoicesGenerator.W2EshopInvoice.web': 'webbadress:',
    'wnd.es.CheckoutShippingService.correiosDeliveryWithSpecialConditions':
      'CEP de destino est\u00e1 sujeito a condi\u00e7\u00f5es especiais de entrega pela ECT e ser\u00e1 realizada com o acr\u00e9scimo de at\u00e9 7 (sete) dias \u00fateis ao prazo regular.',
    'wnd.es.CheckoutShippingService.correiosWithoutHomeDelivery':
      'CEP de destino est\u00e1 temporariamente sem entrega domiciliar. A entrega ser\u00e1 efetuada na ag\u00eancia indicada no Aviso de Chegada que ser\u00e1 entregue no endere\u00e7o do destinat\u00e1rio',
    'wnd.es.ProductEdit.unit.cm': 'cm',
    'wnd.es.ProductEdit.unit.floz': 'fl oz',
    'wnd.es.ProductEdit.unit.ft': 'ft',
    'wnd.es.ProductEdit.unit.ft2': 'ft\u00b2',
    'wnd.es.ProductEdit.unit.g': 'g',
    'wnd.es.ProductEdit.unit.gal': 'gal',
    'wnd.es.ProductEdit.unit.in': 'in',
    'wnd.es.ProductEdit.unit.inventoryQuantity': 'st',
    'wnd.es.ProductEdit.unit.inventorySize': 'cm',
    'wnd.es.ProductEdit.unit.inventorySize.cm': 'cm',
    'wnd.es.ProductEdit.unit.inventorySize.inch': 'tum',
    'wnd.es.ProductEdit.unit.inventoryWeight': 'kg',
    'wnd.es.ProductEdit.unit.inventoryWeight.kg': 'kg',
    'wnd.es.ProductEdit.unit.inventoryWeight.lb': 'pund',
    'wnd.es.ProductEdit.unit.l': 'L',
    'wnd.es.ProductEdit.unit.m': 'm',
    'wnd.es.ProductEdit.unit.m2': 'm\u00b2',
    'wnd.es.ProductEdit.unit.m3': 'm\u00b3',
    'wnd.es.ProductEdit.unit.mg': 'mg',
    'wnd.es.ProductEdit.unit.ml': 'ml',
    'wnd.es.ProductEdit.unit.mm': 'mm',
    'wnd.es.ProductEdit.unit.oz': 'oz',
    'wnd.es.ProductEdit.unit.pcs': 'st',
    'wnd.es.ProductEdit.unit.pt': 'pt',
    'wnd.es.ProductEdit.unit.qt': 'qt',
    'wnd.es.ProductEdit.unit.yd': 'yd',
    'wnd.es.ProductList.inventory.outOfStock': 'Ej i lager',
    'wnd.fe.CheckoutSelectMethodKlarnaPlaygroundItem': '{name} playground test',
    'wnd.fe.CheckoutSelectMethodZasilkovnaItem.change': 'Change pick up point',
    'wnd.fe.CheckoutSelectMethodZasilkovnaItem.choose':
      'Choose your pick up point',
    'wnd.fe.CheckoutSelectMethodZasilkovnaItem.error':
      'Please select a pick up point',
    'wnd.fe.CheckoutZipField.brInvalid':
      'V\u00e4nligen ange ett giltigt postnummer i format XXX XX',
    'wnd.fe.CookieBar.message':
      'Denna webbplats anv\u00e4nder cookies f\u00f6r att f\u00f6rb\u00e4ttra funktionaliteten och anv\u00e4ndbarheten. Genom att anv\u00e4nda v\u00e5r hemsida, accepterar du v\u00e5r integritetspolicy.',
    'wnd.fe.FeFooter.createWebsite': 'Skapa din hemsida gratis!',
    'wnd.fe.FormManager.error.file.notAllowedExtension':
      'Filformatet \u0022{EXTENSION}\u0022 st\u00f6ds inte.',
    'wnd.fe.FormManager.error.file.required': 'V\u00e4nligen v\u00e4lj en fil.',
    'wnd.fe.FormManager.error.file.sizeExceeded':
      'Maxstorleken f\u00f6r uppladdning av fil \u00e4r {SIZE} MB.',
    'wnd.fe.FormManager.error.userChangePassword':
      'L\u00f6senorden matchar inte',
    'wnd.fe.FormManager.error.userLogin.inactiveAccount':
      'Din registrering har \u00e4nnu inte godk\u00e4nts, du kan inte logga in.',
    'wnd.fe.FormManager.error.userLogin.invalidLogin':
      'Felaktigt anv\u00e4ndarnamn (e-post) eller l\u00f6senord!',
    'wnd.fe.FreeBarBlock.buttonText': 'Kom ig\u00e5ng',
    'wnd.fe.FreeBarBlock.longText':
      'Denna hemsidan \u00e4r skapad via Webnode. \u003Cstrong\u003ESkapa din egna\u003C/strong\u003E gratis hemsida idag!',
    'wnd.fe.ListingData.shortMonthName.Apr': 'apr.',
    'wnd.fe.ListingData.shortMonthName.Aug': 'aug.',
    'wnd.fe.ListingData.shortMonthName.Dec': 'dec.',
    'wnd.fe.ListingData.shortMonthName.Feb': 'feb.',
    'wnd.fe.ListingData.shortMonthName.Jan': 'jan.',
    'wnd.fe.ListingData.shortMonthName.Jul': 'jul.',
    'wnd.fe.ListingData.shortMonthName.Jun': 'jun.',
    'wnd.fe.ListingData.shortMonthName.Mar': 'mar.',
    'wnd.fe.ListingData.shortMonthName.May': 'maj',
    'wnd.fe.ListingData.shortMonthName.Nov': 'nov.',
    'wnd.fe.ListingData.shortMonthName.Oct': 'okt.',
    'wnd.fe.ListingData.shortMonthName.Sep': 'sep.',
    'wnd.fe.ShoppingCartManager.count.between2And4': '{COUNT} artiklar',
    'wnd.fe.ShoppingCartManager.count.moreThan5': '{COUNT} artiklar',
    'wnd.fe.ShoppingCartManager.count.one': '{COUNT} artikel',
    'wnd.fe.ShoppingCartTable.label.itemsInStock':
      'Only {COUNT} pcs available in stock',
    'wnd.fe.ShoppingCartTable.label.itemsInStock.between2And4':
      'Endast {COUNT} st. p\u00e5 lager',
    'wnd.fe.ShoppingCartTable.label.itemsInStock.moreThan5':
      'Endast {COUNT} st. p\u00e5 lager',
    'wnd.fe.ShoppingCartTable.label.itemsInStock.one':
      'Endast {COUNT} st. p\u00e5 lager',
    'wnd.fe.ShoppingCartTable.label.outOfStock': 'Tillf\u00e4lligt slut',
    'wnd.fe.UserBar.logOut': 'Logga ut',
    'wnd.pc.BlogDetailPageZone.next': 'Nya inl\u00e4gg',
    'wnd.pc.BlogDetailPageZone.previous': 'Gamla inl\u00e4gg',
    'wnd.pc.ContactInfoBlock.placeholder.infoMail':
      'T.ex. kontakt@minhemsida.se',
    'wnd.pc.ContactInfoBlock.placeholder.infoPhone': 'T.ex. 070002331',
    'wnd.pc.ContactInfoBlock.placeholder.infoText':
      'T.ex. Vi har \u00f6ppet dagligen 09-16',
    'wnd.pc.CookieBar.button.advancedClose': 'St\u00e4ng',
    'wnd.pc.CookieBar.button.advancedOpen':
      '\u00d6ppna avancerade inst\u00e4llningar',
    'wnd.pc.CookieBar.button.advancedSave': 'Spara',
    'wnd.pc.CookieBar.link.disclosure': 'Upplysning',
    'wnd.pc.CookieBar.title.advanced': 'Avancerade inst\u00e4llningar',
    'wnd.pc.CookieBar.title.option.functional': 'Funktionella cookies',
    'wnd.pc.CookieBar.title.option.marketing': 'Marknadsf\u00f6ringscookies',
    'wnd.pc.CookieBar.title.option.necessary': 'N\u00f6dv\u00e4ndiga cookies',
    'wnd.pc.CookieBar.title.option.performance': 'Prestandacookies',
    'wnd.pc.CookieBarReopenBlock.text': 'Cookies ',
    'wnd.pc.FileBlock.download': 'LADDA NER',
    'wnd.pc.FormBlock.action.defaultMessage.text':
      'Formul\u00e4ret har skickats.',
    'wnd.pc.FormBlock.action.defaultMessage.title': 'Tack!',
    'wnd.pc.FormBlock.action.invisibleCaptchaInfoText':
      'Denna hemsidan skyddas av reCAPTCHA och Googles \u003Clink1\u003EIntegritetspolicy\u003C/link1\u003E samt dess \u003Clink2\u003EAnv\u00e4ndarvillkor\u003C/link2\u003E till\u00e4mpas.',
    'wnd.pc.FormBlock.action.submitBlockedDisabledBecauseSiteSecurity':
      'Formul\u00e4ret kan inte skickas (hemsidans \u00e4gare har blockerat din position).',
    'wnd.pc.FormBlock.mail.value.no': 'Nej',
    'wnd.pc.FormBlock.mail.value.yes': 'Ja',
    'wnd.pc.FreeBarBlock.text': 'Skapad med',
    'wnd.pc.ListingDetailPageZone.next': 'N\u00e4sta',
    'wnd.pc.ListingDetailPageZone.previous': 'F\u00f6reg\u00e5ende',
    'wnd.pc.ListingItemCopy.namePrefix': 'Kopia av',
    'wnd.pc.Option.defaultText': 'Nytt val',
    'wnd.pc.PageCopy.namePrefix': 'Kopia av',
    'wnd.pc.PhotoGalleryBlock.placeholder.text':
      'Inga bilder hittades i detta bildgalleri',
    'wnd.pc.PhotoGalleryBlock.placeholder.title': 'Bildgalleri',
    'wnd.pc.ProductAddToCartBlock.addToCart': 'L\u00e4gg i kundvagnen',
    'wnd.pc.ProductAvailability.in14Days': 'Available in 14 days',
    'wnd.pc.ProductAvailability.in3Days': 'Available in 3 days',
    'wnd.pc.ProductAvailability.in7Days': 'Available in 7 days',
    'wnd.pc.ProductAvailability.inMonth': 'Available in 1 month',
    'wnd.pc.ProductAvailability.inMoreThanMonth':
      'Available in more than 1 month',
    'wnd.pc.ProductAvailability.inStock': 'In stock',
    'wnd.pc.ProductGalleryBlock.placeholder.text':
      'Det finns inga bilder i detta produktgalleri.',
    'wnd.pc.ProductGalleryBlock.placeholder.title': 'Produktgalleri',
    'wnd.pc.ProductItem.button.viewDetail': 'Produktsida',
    'wnd.pc.ProductOptionGroupBlock.notSelected': 'Ingen variant vald',
    'wnd.pc.ProductOutOfStockBlock.label': 'Tillf\u00e4lligt slut',
    'wnd.pc.ProductPriceBlock.prefixText': 'Pris fr\u00e5n ',
    'wnd.pc.ProductPriceBlock.suffixText': '',
    'wnd.pc.ProductPriceExcludingVATBlock.USContent': 'priset exkl. moms',
    'wnd.pc.ProductPriceExcludingVATBlock.content': 'priset inkl. moms',
    'wnd.pc.ProductShippingInformationBlock.content': 'exklusive fraktkostnad',
    'wnd.pc.ProductVATInformationBlock.content': 'exkl. moms {PRICE}',
    'wnd.pc.ProductsZone.label.collections': 'Kategorier',
    'wnd.pc.ProductsZone.placeholder.noProductsInCategory':
      'Denna kategori \u00e4r tom. L\u00e4gg till produkter eller v\u00e4lj en annan kategori.',
    'wnd.pc.ProductsZone.placeholder.text':
      'Det finns inga produkter \u00e4nnu. B\u00f6rja med att klicka \u0022L\u00e4gg till produkt\u0022.',
    'wnd.pc.ProductsZone.placeholder.title': 'Produkter',
    'wnd.pc.ProductsZoneModel.label.allCollections': 'Alla produkter',
    'wnd.pc.SearchBlock.allListingItems': 'Alla blogg inl\u00e4gg',
    'wnd.pc.SearchBlock.allPages': 'Alla sidor',
    'wnd.pc.SearchBlock.allProducts': 'Alla produkter',
    'wnd.pc.SearchBlock.allResults': 'Visa alla resultat',
    'wnd.pc.SearchBlock.iconText': 'S\u00f6k',
    'wnd.pc.SearchBlock.inputPlaceholder': 'S\u00f6k...',
    'wnd.pc.SearchBlock.matchInListingItemIdentifier':
      'L\u00e4gg upp med termen \u0022{IDENTIFIER}\u0022 i URL:en',
    'wnd.pc.SearchBlock.matchInPageIdentifier':
      'Page with the term \u0022{IDENTIFIER}\u0022 in URL',
    'wnd.pc.SearchBlock.noResults': 'Inga s\u00f6kresultat hittades',
    'wnd.pc.SearchBlock.requestError':
      'Felmeddelande: Det gick inte att ladda fler resultat. Var god uppdatera sidan eller \u003Clink1\u003Eklicka h\u00e4r och f\u00f6rs\u00f6k igen\u003C/link1\u003E.',
    'wnd.pc.SearchResultsZone.emptyResult':
      'Inga matchade resultat vid din s\u00f6kning. V\u00e4nligen testa med en annan s\u00f6kterm.',
    'wnd.pc.SearchResultsZone.foundProducts': 'Hittade produkter:',
    'wnd.pc.SearchResultsZone.listingItemsTitle': 'Blogg inl\u00e4gg',
    'wnd.pc.SearchResultsZone.pagesTitle': 'Sidor',
    'wnd.pc.SearchResultsZone.productsTitle': 'Produkter',
    'wnd.pc.SearchResultsZone.title': 'S\u00f6kresultat f\u00f6r:',
    'wnd.pc.SectionMsg.name.eshopCategories': 'Kategorier',
    'wnd.pc.ShoppingCartTable.label.checkout': 'Forts\u00e4tt till kassan',
    'wnd.pc.ShoppingCartTable.label.checkoutDisabled':
      'Slutf\u00f6rande av best\u00e4llningen \u00e4r inte tillg\u00e4nglig (ingen frakt eller betalningsmetod)',
    'wnd.pc.ShoppingCartTable.label.checkoutDisabledBecauseSiteSecurity':
      'Orderns kan inte skickas (webbshoppens \u00e4gare har blockerat din position).',
    'wnd.pc.ShoppingCartTable.label.continue': 'Forts\u00e4tt shoppa',
    'wnd.pc.ShoppingCartTable.label.delete': 'Ta bort',
    'wnd.pc.ShoppingCartTable.label.item': 'Produkt',
    'wnd.pc.ShoppingCartTable.label.price': 'Pris',
    'wnd.pc.ShoppingCartTable.label.quantity': 'Antal',
    'wnd.pc.ShoppingCartTable.label.sum': 'Totalt',
    'wnd.pc.ShoppingCartTable.label.totalPrice': 'Totalt',
    'wnd.pc.ShoppingCartTable.placeholder.text':
      'Du kan \u00e4ndra det d\u00e4r! V\u00e4lj n\u00e5got fint.',
    'wnd.pc.ShoppingCartTable.placeholder.title': 'Din kundvagn \u00e4r tom.',
    'wnd.pc.ShoppingCartTotalPriceExcludingVATBlock.label': 'Utan moms',
    'wnd.pc.ShoppingCartTotalPriceInformationBlock.label':
      'Exklusive fraktkostnad',
    'wnd.pc.ShoppingCartTotalPriceWithVATBlock.label': 'Med moms',
    'wnd.pc.ShoppingCartTotalVATBlock.label': 'Moms {RATE}%',
    'wnd.pc.SystemFooterBlock.poweredByWebnode':
      'Skapad med {START_LINK}Webnode{END_LINK}',
    'wnd.pc.UserBar.logoutText': 'Logga ut',
    'wnd.pc.UserChangePasswordFormBlock.invalidRecoveryUrl':
      'L\u00e4nken f\u00f6r att \u00e5terst\u00e4lla ditt l\u00f6senord har utg\u00e5tt. F\u00f6r att generera en ny l\u00e4nk, g\u00e5 till sidan {START_LINK}Gl\u00f6mt l\u00f6senord{END_LINK}',
    'wnd.pc.UserRecoveryFormBlock.action.defaultMessage.text':
      'En l\u00e4nk f\u00f6r \u00e4ndring av l\u00f6senord har skickats till din e-postadress. Om du inte mottar mejlet, kolla i skr\u00e4ppostmappen.',
    'wnd.pc.UserRecoveryFormBlock.action.defaultMessage.title':
      'Mejlet med instruktioner har skickats.',
    'wnd.pc.UserRegistrationFormBlock.action.defaultMessage.text':
      'Din registrering v\u00e4ntar p\u00e5 godk\u00e4nnande. D\u00e5 din registrering godk\u00e4nts, kommer du att bli meddelad om detta via mejl.',
    'wnd.pc.UserRegistrationFormBlock.action.defaultMessage.title':
      'Tack f\u00f6r att du registrerade dig p\u00e5 v\u00e5r hemsida!',
    'wnd.pc.UserRegistrationFormBlock.action.successfulRegistrationMessage.text':
      'Din registrering lyckades och du kan nu logga in p\u00e5 de privata sidorna p\u00e5 denna hemsida.',
    'wnd.pm.AddNewPagePattern.onlineStore': 'Webbshop',
    'wnd.ps.CookieBarSettingsForm.default.advancedMainText':
      'Du kan anpassa dina cookie-val h\u00e4r. Aktivera eller inaktivera f\u00f6ljande kategorier och spara ditt val.',
    'wnd.ps.CookieBarSettingsForm.default.captionAcceptAll': 'Acceptera alla',
    'wnd.ps.CookieBarSettingsForm.default.captionAcceptNecessary':
      'Acceptera endast n\u00f6dv\u00e4ndiga',
    'wnd.ps.CookieBarSettingsForm.default.mainText':
      'Vi anv\u00e4nder cookies f\u00f6r att m\u00f6jligg\u00f6ra en korrekt funktion och s\u00e4kerhet p\u00e5 v\u00e5r hemsida, och f\u00f6r att erbjuda dig b\u00e4sta m\u00f6jliga anv\u00e4ndarupplevelse.',
  },
  fontSubset: null,
};

wnd.trackerConfig = {
  events: {
    error: { name: 'Error' },
    publish: { name: 'Publish page' },
    open_premium_popup: { name: 'Open premium popup' },
    upgrade_your_plan: { name: 'Upgrade your plan' },
    ml_lock_page: { name: 'Lock access to page' },
    ml_unlock_page: { name: 'Unlock access to page' },
    ml_start_add_page_member_area: {
      name: 'Start - add page Member Area',
    },
    ml_end_add_page_member_area: { name: 'End - add page Member Area' },
    ml_show_activation_popup: { name: 'Show activation popup' },
    ml_activation: { name: 'Member Login Activation' },
    ml_deactivation: { name: 'Member Login Deactivation' },
    ml_enable_require_approval: {
      name: 'Enable approve registration manually',
    },
    ml_disable_require_approval: {
      name: 'Disable approve registration manually',
    },
    ml_fe_member_registration: { name: 'Member Registration on FE' },
    ml_fe_member_login: { name: 'Login Member' },
    ml_fe_member_recovery: { name: 'Sent recovery email' },
    ml_fe_member_change_password: { name: 'Change Password' },
    undoredo_click_undo: { name: 'Undo/Redo - click Undo' },
    undoredo_click_redo: { name: 'Undo/Redo - click Redo' },
    add_page: { name: 'Page adding completed' },
    change_page_order: { name: 'Change of page order' },
    delete_page: { name: 'Page deleted' },
    background_options_change: { name: 'Background setting completed' },
    add_content: { name: 'Content adding completed' },
    delete_content: { name: 'Content deleting completed' },
    change_text: { name: 'Editing of text completed' },
    add_image: { name: 'Image adding completed' },
    add_photo: { name: 'Adding photo to galery completed' },
    change_logo: { name: 'Logo changing completed' },
    open_pages: { name: 'Open Pages' },
    show_page_cms: { name: 'Show Page - CMS' },
    new_section: { name: 'New section completed' },
    delete_section: { name: 'Section deleting completed' },
    add_video: { name: 'Video adding completed' },
    add_maps: { name: 'Maps adding completed' },
    add_button: { name: 'Button adding completed' },
    add_file: { name: 'File adding completed' },
    add_hr: { name: 'Horizontal line adding completed' },
    delete_cell: { name: 'Cell deleting completed' },
    delete_microtemplate: { name: 'Microtemplate deleting completed' },
    add_blog_page: { name: 'Blog page adding completed' },
    new_blog_post: { name: 'New blog post created' },
    new_blog_recent_posts: { name: 'Blog recent posts list created' },
    e_show_products_popup: { name: 'Show products popup' },
    e_show_add_product: { name: 'Show add product popup' },
    e_show_edit_product: { name: 'Show edit product popup' },
    e_show_collections_popup: { name: 'Show collections manager popup' },
    e_show_eshop_settings: { name: 'Show eshop settings popup' },
    e_add_product: { name: 'Add product' },
    e_edit_product: { name: 'Edit product' },
    e_remove_product: { name: 'Remove product' },
    e_bulk_show: { name: 'Bulk show products' },
    e_bulk_hide: { name: 'Bulk hide products' },
    e_bulk_remove: { name: 'Bulk remove products' },
    e_move_product: { name: 'Order products' },
    e_add_collection: { name: 'Add collection' },
    e_rename_collection: { name: 'Rename collection' },
    e_remove_collection: { name: 'Remove collection' },
    e_add_product_to_collection: { name: 'Assign product to collection' },
    e_remove_product_from_collection: {
      name: 'Unassign product from collection',
    },
    e_move_collection: { name: 'Order collections' },
    e_add_products_page: { name: 'Add products page' },
    e_add_procucts_section: { name: 'Add products list section' },
    e_add_products_content: { name: 'Add products list content block' },
    e_change_products_zone_style: {
      name: 'Change style in products list',
    },
    e_change_products_zone_collection: {
      name: 'Change collection in products list',
    },
    e_show_products_zone_collection_filter: {
      name: 'Show collection filter in products list',
    },
    e_hide_products_zone_collection_filter: {
      name: 'Hide collection filter in products list',
    },
    e_show_product_detail_page: { name: 'Show product detail page' },
    e_add_to_cart: { name: 'Add product to cart' },
    e_remove_from_cart: { name: 'Remove product from cart' },
    e_checkout_step: { name: 'From cart to checkout' },
    e_finish_checkout: { name: 'Finish order' },
    welcome_window_play_video: { name: 'Welcome window - play video' },
    e_import_file: { name: 'Eshop - products import - file info' },
    e_import_upload_time: {
      name: 'Eshop - products import - upload file duration',
    },
    e_import_result: { name: 'Eshop - products import result' },
    e_import_error: { name: 'Eshop - products import - errors' },
    e_promo_blogpost: { name: 'Eshop promo - blogpost' },
    e_promo_activate: { name: 'Eshop promo - activate' },
    e_settings_activate: { name: 'Online store - activate' },
    e_promo_hide: { name: 'Eshop promo - close' },
    e_activation_popup_step: { name: 'Eshop activation popup - step' },
    e_activation_popup_activate: {
      name: 'Eshop activation popup - activate',
    },
    e_activation_popup_hide: { name: 'Eshop activation popup - close' },
    e_deactivation: { name: 'Eshop deactivation' },
    e_reactivation: { name: 'Eshop reactivation' },
    e_variant_create_first: {
      name: 'Eshop - variants - add first variant',
    },
    e_variant_add_option_row: {
      name: 'Eshop - variants - add option row',
    },
    e_variant_remove_option_row: {
      name: 'Eshop - variants - remove option row',
    },
    e_variant_activate_edit: { name: 'Eshop - variants - activate edit' },
    e_variant_deactivate_edit: {
      name: 'Eshop - variants - deactivate edit',
    },
    move_block_popup: { name: 'Move block - show popup' },
    move_block_start: { name: 'Move block - start' },
    publish_window: { name: 'Publish window' },
    welcome_window_video: { name: 'Video welcome window' },
    cookiebar_show: { name: 'Cookiebar was shown' },
    cookiebar_accept_all: { name: 'User accepted all cookies' },
    cookiebar_accept_necessary: {
      name: 'User accepted necessary cookies',
    },
  },
  data: {
    user: { u: 0, p: 43384820, lc: 'SE', t: '1' },
    action: {
      identifier: '',
      name: '',
      category: 'project',
      platform: 'WND2',
      version: '2-1607_2-1607',
    },
    browser: {
      url: 'https://www.hittakonkurser.se/',
      ua: '2ip bot/1.1 (+https://2ip.io)',
      referer_url: 'https://hittakonkurser.se',
      resolution: '',
      ip: '84.246.85.11',
    },
  },
  urlPrefix: 'https://events.webnode.com/projects/-/events/',
  collection: 'PROD',
};
